// Command ic is the Infinite Correspondence server and admin CLI.
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"log/slog"
	"os"
	"strconv"

	"github.com/jackc/pgx/v5"

	"github.com/nairwolf/4545-correspondence/internal/config"
	"github.com/nairwolf/4545-correspondence/internal/db"
	"github.com/nairwolf/4545-correspondence/internal/db/gen"
	"github.com/nairwolf/4545-correspondence/internal/lichess"
)

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "ic:", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	if len(args) == 0 {
		return errors.New("usage: ic <serve|migrate|refresh-ratings|seed-players|import-pairings|sync-games|recompute|generate-round|publish-round|setting> ...")
	}

	cfg, err := config.Load()
	if err != nil {
		return err
	}

	ctx := context.Background()

	switch args[0] {
	case "migrate":
		return runMigrate(ctx, cfg)
	case "serve":
		return runServe(ctx, cfg)
	case "refresh-ratings":
		pool, err := db.Open(ctx, cfg.DatabaseURL)
		if err != nil {
			return err
		}
		defer pool.Close()
		return runRefreshRatings(ctx, pool, lichess.New(cfg.LichessToken), nil)
	case "seed-players":
		if len(args) < 2 {
			return errors.New("usage: ic seed-players <usernames-file>")
		}
		pool, err := db.Open(ctx, cfg.DatabaseURL)
		if err != nil {
			return err
		}
		defer pool.Close()
		return runSeedPlayers(ctx, pool, lichess.New(cfg.LichessToken), args[1])
	case "import-pairings":
		fs := flag.NewFlagSet("import-pairings", flag.ContinueOnError)
		pairAt := fs.String("pair-at", "", "RFC3339 timestamp; defaults to the most recent Monday 12:00 UTC")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		if fs.NArg() < 1 {
			return errors.New("usage: ic import-pairings [--pair-at RFC3339] <pairings.csv>")
		}
		pool, err := db.Open(ctx, cfg.DatabaseURL)
		if err != nil {
			return err
		}
		defer pool.Close()
		return runImportPairings(ctx, pool, fs.Arg(0), *pairAt)
	case "sync-games":
		pool, err := db.Open(ctx, cfg.DatabaseURL)
		if err != nil {
			return err
		}
		defer pool.Close()
		return runSyncGames(ctx, pool, lichess.New(cfg.LichessToken), nil)
	case "recompute":
		pool, err := db.Open(ctx, cfg.DatabaseURL)
		if err != nil {
			return err
		}
		defer pool.Close()
		return runRecompute(ctx, pool, nil)
	case "generate-round":
		pool, err := db.Open(ctx, cfg.DatabaseURL)
		if err != nil {
			return err
		}
		defer pool.Close()
		// generated_by = manual: a round generated by hand is an
		// exception (spec §6.1), and the admin round list says which
		// rounds were. No scheduler: the CLI has no job runner, so a
		// draft is published by serve's hourly sweep.
		return runGenerateRound(ctx, pool, gen.RoundSourceManual, nil, nil)
	case "publish-round":
		if len(args) < 2 {
			return errors.New("usage: ic publish-round <round-number>")
		}
		pool, err := db.Open(ctx, cfg.DatabaseURL)
		if err != nil {
			return err
		}
		defer pool.Close()
		return publishRoundByNumber(ctx, pool, args[1])
	case "setting":
		if len(args) < 3 {
			return errors.New(`usage: ic setting <key> <json-value>   (e.g. ic setting pairing.review_window_hours 24)`)
		}
		pool, err := db.Open(ctx, cfg.DatabaseURL)
		if err != nil {
			return err
		}
		defer pool.Close()
		return runSetting(ctx, pool, args[1], args[2])
	default:
		return fmt.Errorf(
			"unknown command %q (want: serve, migrate, refresh-ratings, seed-players, import-pairings, sync-games, recompute, generate-round, publish-round, setting)",
			args[0],
		)
	}
}

// publishRoundByNumber resolves the round number an admin would quote
// — the one on /standings and in the round list — to the id the job
// works in. A cancelled round no longer holds its number, so this can
// only ever find a live one.
func publishRoundByNumber(ctx context.Context, db txBeginner, arg string) error {
	number, err := strconv.Atoi(arg)
	if err != nil {
		return fmt.Errorf("publish-round: %q is not a round number", arg)
	}
	round, err := gen.New(db).GetRoundByNumber(ctx, int32(number))
	if errors.Is(err, pgx.ErrNoRows) {
		return fmt.Errorf("publish-round: no round %d", number)
	}
	if err != nil {
		return fmt.Errorf("publish-round: look up round %d: %w", number, err)
	}
	return runPublishRound(ctx, db, round.ID, nil)
}

func runMigrate(ctx context.Context, cfg config.Config) error {
	pool, err := db.Open(ctx, cfg.DatabaseURL)
	if err != nil {
		return err
	}
	defer pool.Close()

	if err := db.Migrate(ctx, pool, cfg.DatabaseURL); err != nil {
		return err
	}
	slog.Info("migrations applied")
	return nil
}
